#
# By Owen
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for shadowsocks
LUCI_DEPENDS:=+shadowsocks

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

