#!/bin/sh /etc/rc.common


START=80

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

genconf() {

	[ -f /etc/config/ssrlocal ] || {
		echo "You are missing configuration file /etc/config/ssrlocal"
		return 1
	}

	config_load "ssrlocal"

	config_get S_ENABLED config enabled

	[ "$S_ENABLED" == "0" ] && {
		echo "ssrlocal is disabled."
		exit 0
	}

	config_get S_SERVER config server
	config_get S_SERVER_PORT config server_port
	config_get S_LOCAL_PORT config local_port
	config_get S_METHOD config method
	config_get S_PASSWORD config password
	config_get S_TIMEOUT config timeout
	config_get S_PROTOCOL config protocol
	config_get S_OBFS config obfs	
	config_get S_OBFS_PARAM config obfs_param	
	config_get S_PROTOCOL_PARAM config protocol_param
				
	
	
	

	cat >/etc/ssrlocal.json <<EOF
{
    "server": "$S_SERVER",
    "server_port": $S_SERVER_PORT,
    "password": "$S_PASSWORD",
    "method": "$S_METHOD",
    "local_address": "0.0.0.0",
    "local_port": $S_LOCAL_PORT,
    "timeout": $S_TIMEOUT,
    "protocol": "$S_PROTOCOL",
    "protocol_param": "$S_PROTOCOL_PARAM",
    "obfs": "$S_OBFS",
    "obfs_param": "$S_OBFS_PARAM",    
}

EOF
}

start() {
  genconf
  CONFIG=/etc/ssrlocal.json  
	service_start /usr/bin/ssrlocal -c $CONFIG
	sleep 1
}

restart() {
stop
sleep 1
start
}


stop() {
	service_stop /usr/bin/ssrlocal
	sleep 1
	}
